### ISSUE TITLE
请求提供 RSS

### ISSUE THREAD

**Issue by cxumol** [spencerwooo/spencerwooo.github.io#83]
观赏贵博几篇文章, 颇受启发｡ 想长期跟进, 却未发现 RSS 订阅地址｡ 在下建议提供 RSS, 因为: 

1. 多数博客默认启用 RSS 订阅｡ 开通 RSS 订阅, 能养成长期读者, 也能增加传播性｡ 
2. 即使当前 vuepress 少见于博客, 仍能在 github 上找得到用于该系统的 RSS feed 轮子 ([其一](https://github.com/youngtailors/vuepress-plugin-rss), [其二](https://github.com/webmasterish/vuepress-plugin-feed))｡ 想必技术上实现也不会太困难｡ 

希望您能考虑这项建议｡

**Comment by spencerwooo** [comment]
博客今后大概率不会更新知识或技术性的文章了。还请直接在少数派看我的文章：<https://sspai.com/user/800610/posts>，感谢支持。

少数派 RSS 为：https://sspai.com/feed
